name: Extract missing db files
on:
  pull_request:
    branches:
    - main
jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: CMS OD with cvmfs for condition db search
    steps:
      # checkout the files of this repository
      - uses: actions/checkout@v2
      - uses: cvmfs-contrib/github-action-cvmfs@v2
        with:
          cvmfs_repositories: 'cms-opendata-conddb.cern.ch'
      - name: Test CernVM-FS
        run: | 
          ls /cvmfs/cms-opendata-conddb.cern.ch
          mkdir outputs
      - name: Start CMS OD container
        #run: docker run -v $(pwd):/mnt/vol -v /cvmfs:/cvmfs -w /home/cmsusr cmsopendata/cmssw_5_3_32_vnc /bin/bash  /mnt/vol/workflow_test.sh PhysObjectExtractorTool master PhysObjectExtractor/JEC/jec_py.cfg FT53_V21A_AN6_FULL cms-legacydata-analyses
        run: | 
          # docker run -v $(pwd):/mnt/vol -v /cvmfs:/cvmfs -w /home/cmsusr cmsopendata/cmssw_5_3_32_vnc /bin/bash  /mnt/vol/workflow_test.sh
          docker run -v $(pwd):/mnt/vol -v /cvmfs:/cvmfs -w /home/cmsusr cmsopendata/cmssw_5_3_32_vnc /bin/bash  /mnt/vol/workflow_test.sh PhysObjectExtractorTool 2011-data-mc PhysObjectExtractor/python/poet_cfg.py START53_LV6A1 
          #docker run -v $(pwd):/mnt/vol -v /cvmfs:/cvmfs -w /home/cmsusr cmsopendata/cmssw_5_3_32_vnc /bin/bash  /mnt/vol/workflow_test.sh PhysObjectExtractorTool master PhysObjectExtractor/python/poet_cfg_mc_2012.py START53_V27 
          #cp -r /mnt/vol/products outputs
        #upload output file
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: outputs/
