name: Extract missing db files
on:
  pull_request:
    branches:
    - main
jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: CMS OD with cvmfs for condition db search
    steps:
      # checkout the files of this repository
      - uses: actions/checkout@v3
      - uses: cvmfs-contrib/github-action-cvmfs@v3
        with:
          cvmfs_repositories: 'cms-opendata-conddb.cern.ch'
      - name: Test CernVM-FS
        run: | 
          ls /cvmfs/cms-opendata-conddb.cern.ch
          mkdir outputs
      - name: Start CMS OD container
        run: | 
          docker run -v $(pwd):/mnt/vol -v /cvmfs:/mountedcvmfs -w /home/cmsusr cmsopendata/cmssw_5_3_32-slc6_amd64_gcc472 /bin/bash  /mnt/vol/workflow_test.sh PhysObjectExtractorTool 2012 PhysObjectExtractor/python/poet_cfg_data_pat.py FT53_V21A_AN6_FULL katilp
          #cp -r /mnt/vol/products outputs
        # upload output file
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: outputs/
